upload:
  path: D:/static/
server:
  #  port: 8082
  #  address: 127.0.0.1
  port: 8000
  address: 0.0.0.0
  servlet:
    context-path: /
spring:
  datasource:
    #    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    url: jdbc:oracle:thin:@118.31.11.163:1521:helowin
    username: food
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  resources:
    static-locations: classpath:/static/,file:${upload.path}
  mvc:
    static-path-pattern: /res/**


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:repository/*.xml
